Repository ahmdtrdi/backend-warongwarem, pull requests merged in 2023-12, with the labels that each got.

#13 feat: made APIs Reservations
  app/Http/Controllers/ReservationController.php
  app/Models/Reservation.php
  routes/api.php
Labels: enhancement

#15 feat: add new and modify controller and API
  app/Http/Controllers/RegisterController.php
  app/Http/Controllers/ReservationController.php
  routes/api.php
Labels: enhancement

#16 feat: modify userController register function
  app/Http/Controllers/UserController.php
Labels: enhancement

#17 feat: modify quite few files
  app/Exceptions/Handler.php
  app/Http/Controllers/UserController.php
  app/Http/Middleware/Authenticate.php
  app/Models/User.php
  config/auth.php
  database/migrations/4_add_api_token_to_users_table.php
  routes/api.php
Labels: enhancement

#18 feat: adjust tables with updated ui
  app/Models/User.php
  database/migrations/1_create_users_table.php
  database/migrations/5_create_payment_table.php
Labels: enhancement

#19 Feature/triadi/modify migration database
  app/Exceptions/Handler.php
  app/Http/Controllers/RegisterController.php
  app/Http/Controllers/UserController.php
  routes/api.php
Labels: bug, good first issue

#20 feat: add and modify few files before deployment
  Dockerfile
  app/Http/Controllers/tablesController.php
  app/Models/Reservation.php
  app/Models/Table.php
  database/migrations/6_create_table_list.php
  docker-compose.yml
  docker/nginx.conf
  docker/startup.sh
  routes/api.php
Labels: enhancement

#21 Feature/triadi/modify controllers
  app/Console/Kernel.php
  app/Http/Controllers/ReservationController.php
  app/Http/Controllers/UserController.php
  app/Http/Controllers/tablesController.php
  app/Models/Reservation.php
  app/Models/User.php
  database/migrations/3_create_reservation_table.php
  routes/api.php
  tests/Feature/ExampleTest.php
  tests/Feature/ReservationTest.php
Labels: bug, enhancement, invalid

#25 feat: modify controllers
  .gitignore
  app/Http/Controllers/ReservationController.php
  app/Http/Controllers/UserController.php
  app/Http/Controllers/tablesController.php
  app/Models/Reservation.php
  app/Models/Table.php
  database/migrations/2019_12_14_000001_create_personal_access_tokens_table.php
  database/migrations/2_create_table_list.php
  database/migrations/3_create_reservation_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/TableListSeeder.php
  database/seeders/UsersReservationsSeeder.php
  routes/api.php
Labels: bug, enhancement, wontfix

#26 feat: make jwt token for user and reservation controller
  app/Http/Controllers/ReservationController.php
  app/Http/Controllers/UserController.php
  app/Models/User.php
  composer.json
  composer.lock
  config/cors.php
  config/jwt.php
  config/sanctum.php
Labels: enhancement

#30 Feature/regina/integration
  app/Http/Controllers/UserController.php
Labels: enhancement

#31 feat: in progress of making jwt works
  app/Http/Controllers/ReservationController.php
  app/Http/Kernel.php
  app/Http/Middleware/Authenticate.php
  routes/api.php
Labels: enhancement
